hkex_urls:
  participants:
    chi: https://www.hkexnews.hk/sdw/search/partlist_c.aspx?sortby=partid&shareholdingdate={}
    eng: https://www.hkexnews.hk/sdw/search/partlist.aspx?sortby=partid&shareholdingdate={}
  stocks:
    chi: https://www.hkexnews.hk/sdw/search/stocklist_c.aspx?sortby=stockcode&shareholdingdate={}
    eng: https://www.hkexnews.hk/sdw/search/stocklist.aspx?sortby=stockcode&shareholdingdate={}
  stock_connect:
    hk: https://www.hkexnews.hk/sdw/search/mutualmarket.aspx?t=hk
    sh: https://www.hkexnews.hk/sdw/search/mutualmarket.aspx?t=sh
    sz: https://www.hkexnews.hk/sdw/search/mutualmarket.aspx?t=sz
  main:
    ch: https://www.hkexnews.hk/sdw/search/searchsdw_c.aspx

etnet_latest_price_url: http://10.200.22.176/StreamServer/QuoteSearchServlet?code={}&fieldid=34
etnet_prev_close_price_url: http://10.200.22.176/StreamServer/QuoteSearchServlet?code={}&fieldid=49
etnet_trade_days_url: http://10.1.8.158/StreamServer/QuoteSearchServlet?code=17&fieldid=108

log_file_path: C:\Users\marcus\PycharmProjects\ccass_dayend\ccass.log

scheduler:
  stockcodes: '0 4 * * *'
  participants: '1 4 * * *'
  stock_connect: '3 4 * * *'
  main : '5 4 * * *'
  all_func :  '0 5 * * 1-5'

parameters:
  main:
      max_requests : 40
      check_stockcode: 00700
      back_day: 1
  stock_connect:
      backtract_day: 1
      to_db: True
  stocks:
      backtract_day: 1
      to_db: True
  participants:
      backtract_day: 1
      to_db: True

db:
  host: 10.1.8.208
  port: 3306
  user: root
  password: abcd1234
  schema: ccass_dev
  tables:
    stocks: stocks
    participants: participants
    stock_connect: stock_connect
    summary: summary
    main: main


abbv:
  participant:
    ccass_id : XXXXXX
